// <auto-generated />
namespace PASSION_PROJECT_MVP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedfields));
        
        string IMigrationMetadata.Id
        {
            get { return "202103052306284_updated-fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
